# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_optionsMenu(object):
    def setupUi(self, optionsMenu):
        optionsMenu.setObjectName("optionsMenu")
        optionsMenu.resize(400, 340)
        optionsMenu.setAutoFillBackground(False)
        optionsMenu.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(203, 159, 1, 255), stop:1 rgba(255, 204, 3, 255));")
        self.volumeHorizontalSlider = QtWidgets.QSlider(optionsMenu)
        self.volumeHorizontalSlider.setGeometry(QtCore.QRect(150, 50, 191, 22))
        self.volumeHorizontalSlider.setSliderPosition(50)
        self.volumeHorizontalSlider.setTracking(True)
        self.volumeHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeHorizontalSlider.setObjectName("volumeHorizontalSlider")
        self.labelVolume = QtWidgets.QLabel(optionsMenu)
        self.labelVolume.setGeometry(QtCore.QRect(50, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVolume.setFont(font)
        self.labelVolume.setStyleSheet("background-color: rgb(56, 106, 187);\n"
"color: rgb(255, 255, 255);")
        self.labelVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVolume.setObjectName("labelVolume")
        self.saveButton = QtWidgets.QPushButton(optionsMenu)
        self.saveButton.setGeometry(QtCore.QRect(50, 110, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("background-color: rgb(56, 106, 187);")
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(optionsMenu)
        self.loadButton.setGeometry(QtCore.QRect(50, 160, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadButton.setFont(font)
        self.loadButton.setStyleSheet("background-color: rgb(56, 106, 187);")
        self.loadButton.setObjectName("loadButton")
        self.commandsButton = QtWidgets.QPushButton(optionsMenu)
        self.commandsButton.setGeometry(QtCore.QRect(50, 210, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.commandsButton.setFont(font)
        self.commandsButton.setStyleSheet("background-color: rgb(56, 106, 187);")
        self.commandsButton.setObjectName("commandsButton")
        self.closeButton = QtWidgets.QPushButton(optionsMenu)
        self.closeButton.setGeometry(QtCore.QRect(50, 260, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("background-color: rgb(56, 106, 187);")
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(optionsMenu)
        QtCore.QMetaObject.connectSlotsByName(optionsMenu)

    def retranslateUi(self, optionsMenu):
        _translate = QtCore.QCoreApplication.translate
        optionsMenu.setWindowTitle(_translate("optionsMenu", "Form"))
        self.labelVolume.setText(_translate("optionsMenu", "Volume"))
        self.saveButton.setText(_translate("optionsMenu", "SAVE GAME"))
        self.loadButton.setText(_translate("optionsMenu", "LOAD GAME"))
        self.commandsButton.setText(_translate("optionsMenu", "COMMANDS"))
        self.closeButton.setText(_translate("optionsMenu", "EXIT TO DESKTOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    optionsMenu = QtWidgets.QWidget()
    ui = Ui_optionsMenu()
    ui.setupUi(optionsMenu)
    optionsMenu.show()
    sys.exit(app.exec_())
