# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_for_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pykemon_MainWindow(object):
    def setupUi(self, Pykemon_MainWindow):
        Pykemon_MainWindow.setObjectName("Pykemon_MainWindow")
        Pykemon_MainWindow.setEnabled(True)
        Pykemon_MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pykemon_MainWindow.sizePolicy().hasHeightForWidth())
        Pykemon_MainWindow.setSizePolicy(sizePolicy)
        Pykemon_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        Pykemon_MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/py_symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pykemon_MainWindow.setWindowIcon(icon)
        Pykemon_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        Pykemon_MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Pykemon_MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainMenu = QtWidgets.QWidget(self.centralwidget)
        self.MainMenu.setEnabled(False)
        self.MainMenu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainMenu.setObjectName("MainMenu")
        self.gridLayout.addWidget(self.MainMenu, 0, 0, 1, 1)
        Pykemon_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Pykemon_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        Pykemon_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Pykemon_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Pykemon_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Pykemon_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Pykemon_MainWindow)

    def retranslateUi(self, Pykemon_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Pykemon_MainWindow.setWindowTitle(_translate("Pykemon_MainWindow", "Pykémon : Attrapy-les tous !"))
import gui_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pykemon_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Pykemon_MainWindow()
    ui.setupUi(Pykemon_MainWindow)
    Pykemon_MainWindow.show()
    sys.exit(app.exec_())
