# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransformWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 651, 161))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(120, 40, 81, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 80, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 191, 17))
        self.label_3.setObjectName("label_3")
        self.lonField = QtWidgets.QLineEdit(self.groupBox)
        self.lonField.setGeometry(QtCore.QRect(210, 32, 113, 31))
        self.lonField.setObjectName("lonField")
        self.latField = QtWidgets.QLineEdit(self.groupBox)
        self.latField.setGeometry(QtCore.QRect(210, 70, 113, 31))
        self.latField.setObjectName("latField")
        self.listInputCrs = QtWidgets.QComboBox(self.groupBox)
        self.listInputCrs.setGeometry(QtCore.QRect(210, 110, 311, 41))
        self.listInputCrs.setObjectName("listInputCrs")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 651, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(180, 40, 31, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(180, 70, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 251, 17))
        self.label_6.setObjectName("label_6")
        self.xField = QtWidgets.QLineEdit(self.groupBox_2)
        self.xField.setGeometry(QtCore.QRect(220, 30, 301, 25))
        self.xField.setObjectName("xField")
        self.yField = QtWidgets.QLineEdit(self.groupBox_2)
        self.yField.setGeometry(QtCore.QRect(220, 60, 301, 25))
        self.yField.setObjectName("yField")
        self.listeCRS = QtWidgets.QComboBox(self.groupBox_2)
        self.listeCRS.setGeometry(QtCore.QRect(220, 100, 301, 41))
        self.listeCRS.setObjectName("listeCRS")
        self.addBouton = QtWidgets.QPushButton(self.groupBox_2)
        self.addBouton.setGeometry(QtCore.QRect(530, 110, 89, 25))
        self.addBouton.setObjectName("addBouton")
        self.pasteBouton = QtWidgets.QPushButton(self.groupBox_2)
        self.pasteBouton.setGeometry(QtCore.QRect(530, 50, 89, 25))
        self.pasteBouton.setToolTip("")
        self.pasteBouton.setObjectName("pasteBouton")
        self.transformBouton = QtWidgets.QPushButton(self.centralwidget)
        self.transformBouton.setGeometry(QtCore.QRect(220, 370, 261, 41))
        self.transformBouton.setObjectName("transformBouton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transformation de coordonées"))
        self.groupBox.setTitle(_translate("MainWindow", "Input coordinates:"))
        self.label.setText(_translate("MainWindow", "Longitude:"))
        self.label_2.setText(_translate("MainWindow", "Latitude:"))
        self.label_3.setText(_translate("MainWindow", "Input coordinate system:"))
        self.lonField.setText(_translate("MainWindow", "-1.511400"))
        self.latField.setText(_translate("MainWindow", "48.636002"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output coordinates"))
        self.label_4.setText(_translate("MainWindow", "X:"))
        self.label_5.setText(_translate("MainWindow", "Y:"))
        self.label_6.setText(_translate("MainWindow", "Output coordinate system:"))
        self.addBouton.setText(_translate("MainWindow", "+"))
        self.pasteBouton.setText(_translate("MainWindow", "ᐉ"))
        self.transformBouton.setText(_translate("MainWindow", "Transformer"))
