# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_for_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pykemon_MainWindow(object):
    def setupUi(self, Pykemon_MainWindow):
        Pykemon_MainWindow.setObjectName("Pykemon_MainWindow")
        Pykemon_MainWindow.setEnabled(True)
        Pykemon_MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        QtGui.QFontDatabase.addApplicationFont("fonts/Retro_Gaming.ttf")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pykemon_MainWindow.sizePolicy().hasHeightForWidth())
        Pykemon_MainWindow.setSizePolicy(sizePolicy)
        Pykemon_MainWindow.setMinimumSize(QtCore.QSize(720, 1280))
        Pykemon_MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/py_symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pykemon_MainWindow.setWindowIcon(icon)
        Pykemon_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        Pykemon_MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Pykemon_MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainMenu = QtWidgets.QWidget(self.centralwidget)
        self.MainMenu.setEnabled(False)
        self.MainMenu.setStyleSheet("")
        self.MainMenu.setObjectName("MainMenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainMenu)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MainMenu_PushButton = QtWidgets.QPushButton(self.MainMenu)
        self.MainMenu_PushButton.setEnabled(False)
        self.MainMenu_PushButton.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.MainMenu_PushButton.setObjectName("MainMenu_PushButton")
        self.gridLayout_2.addWidget(self.MainMenu_PushButton, 0, 0, 1, 1)
        self.MainMenu_ClickToStart = QtWidgets.QLabel(self.MainMenu)
        font = QtGui.QFont()
        font.setFamily("Retro Gaming")
        font.setPointSize(int(14*self.ratio))   # Important to have fontSize with ratio.
        font.setBold(True)
        font.setWeight(75)
        self.MainMenu_ClickToStart.setFont(font)
        self.MainMenu_ClickToStart.setScaledContents(True)
        self.MainMenu_ClickToStart.setObjectName("MainMenu_ClickToStart")
        self.gridLayout_2.addWidget(self.MainMenu_ClickToStart, 2, 0, 1, 1)
        self.MainMenu_Logo = QtWidgets.QLabel(self.MainMenu)
        self.MainMenu_Logo.setScaledContents(True)
        self.MainMenu_Logo.setObjectName("MainMenu_Logo")
        self.gridLayout_2.addWidget(self.MainMenu_Logo, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.MainMenu, 0, 0, 1, 1)
        Pykemon_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Pykemon_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 21))
        self.menubar.setObjectName("menubar")
        Pykemon_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Pykemon_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Pykemon_MainWindow.setStatusBar(self.statusbar)
        Pykemon_MainWindow.showMaximized()

        self.retranslateUi(Pykemon_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Pykemon_MainWindow)

    def retranslateUi(self, Pykemon_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Pykemon_MainWindow.setWindowTitle(_translate("Pykemon_MainWindow", "Pykémon : Attrapy-les tous !"))
        self.MainMenu_PushButton.setText(_translate("Pykemon_MainWindow", "PushButton"))
        self.MainMenu_ClickToStart.setText(_translate("Pykemon_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#386abb;\">CLICK ON THE WINDOW TO START</span></p></body></html>"))
        self.MainMenu_Logo.setText(_translate("Pykemon_MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/logos/main_logo.png\"/></p></body></html>"))
import gui_resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pykemon_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Pykemon_MainWindow()
    # Créer une fonction pour automatiser le resize
    screen = app.primaryScreen()
    size = screen.size()
    Pykemon_MainWindow.resize(size.width(), size.height())
    ui.ratio = size.width()/1920
    print(size.width())

    ui.setupUi(Pykemon_MainWindow)
    Pykemon_MainWindow.show()

    sys.exit(app.exec_())
